package basic

// generated by gen.js, don't edit

const NUM_RANKS = 8
const NUM_FILES = 8

const BOARD_AREA = NUM_RANKS * NUM_FILES

const RANK_STORAGE_SIZE_IN_BITS = 3
const FILE_STORAGE_SIZE_IN_BITS = 3

const SQUARE_STORAGE_SIZE_IN_BITS = RANK_STORAGE_SIZE_IN_BITS + FILE_STORAGE_SIZE_IN_BITS

const RANK_SHIFT_IN_BITS = FILE_STORAGE_SIZE_IN_BITS
const FILE_SHIFT_IN_BITS = 0

const RANK_MASK = ((1 << RANK_STORAGE_SIZE_IN_BITS) - 1) << RANK_SHIFT_IN_BITS
const FILE_MASK = (1 << FILE_STORAGE_SIZE_IN_BITS) - 1

type Rank int
type File int
type Square int

const (
   SquareA1 = Square(0)
   SquareB1 = Square(1)
   SquareC1 = Square(2)
   SquareD1 = Square(3)
   SquareE1 = Square(4)
   SquareF1 = Square(5)
   SquareG1 = Square(6)
   SquareH1 = Square(7)
   SquareA2 = Square(8)
   SquareB2 = Square(9)
   SquareC2 = Square(10)
   SquareD2 = Square(11)
   SquareE2 = Square(12)
   SquareF2 = Square(13)
   SquareG2 = Square(14)
   SquareH2 = Square(15)
   SquareA3 = Square(16)
   SquareB3 = Square(17)
   SquareC3 = Square(18)
   SquareD3 = Square(19)
   SquareE3 = Square(20)
   SquareF3 = Square(21)
   SquareG3 = Square(22)
   SquareH3 = Square(23)
   SquareA4 = Square(24)
   SquareB4 = Square(25)
   SquareC4 = Square(26)
   SquareD4 = Square(27)
   SquareE4 = Square(28)
   SquareF4 = Square(29)
   SquareG4 = Square(30)
   SquareH4 = Square(31)
   SquareA5 = Square(32)
   SquareB5 = Square(33)
   SquareC5 = Square(34)
   SquareD5 = Square(35)
   SquareE5 = Square(36)
   SquareF5 = Square(37)
   SquareG5 = Square(38)
   SquareH5 = Square(39)
   SquareA6 = Square(40)
   SquareB6 = Square(41)
   SquareC6 = Square(42)
   SquareD6 = Square(43)
   SquareE6 = Square(44)
   SquareF6 = Square(45)
   SquareG6 = Square(46)
   SquareH6 = Square(47)
   SquareA7 = Square(48)
   SquareB7 = Square(49)
   SquareC7 = Square(50)
   SquareD7 = Square(51)
   SquareE7 = Square(52)
   SquareF7 = Square(53)
   SquareG7 = Square(54)
   SquareH7 = Square(55)
   SquareA8 = Square(56)
   SquareB8 = Square(57)
   SquareC8 = Square(58)
   SquareD8 = Square(59)
   SquareE8 = Square(60)
   SquareF8 = Square(61)
   SquareG8 = Square(62)
   SquareH8 = Square(63)
)

const (
   Rank1 = Rank(0)
   Rank2 = Rank(1)
   Rank3 = Rank(2)
   Rank4 = Rank(3)
   Rank5 = Rank(4)
   Rank6 = Rank(5)
   Rank7 = Rank(6)
   Rank8 = Rank(7)
)

const (
   FileA = File(0)
   FileB = File(1)
   FileC = File(2)
   FileD = File(3)
   FileE = File(4)
   FileF = File(5)
   FileG = File(6)
   FileH = File(7)
)

var RankLetterOf = [NUM_RANKS]string{"1" , "2" , "3" , "4" , "5" , "6" , "7" , "8"}
var FileLetterOf = [NUM_FILES]string{"a" , "b" , "c" , "d" , "e" , "f" , "g" , "h"}

var UCIOf [BOARD_AREA]string
var UCIToSquare map[string]Square

